templates:
  - perl:
    - vhost_perl.template
  - php:
    - vhost_php.template
  - python: 
    - vhost_python.template
  - ruby: 
    - vhost_ruby.template
  - static: 
    - vhost_static.template

modules: 
  - '${PRO_NAME}.conf'
